<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>Test suites containing all test cases related to APIs with update method (PUT, PATCH) and delete (DELETE)</description>
   <name>TS - UPDATE</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>afe16472-25b2-4f55-a0bb-4f2669d700ba</testSuiteGuid>
   <testCaseLink>
      <guid>d18754f9-2403-4d47-9eb4-54e54f7076e3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC UPDATE (PATCH - PUT)/PATCH - Update User</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f0ad3be8-5a9f-4cfc-9bb4-aa9e98094297</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>52fddbe8-5a90-4a00-b74a-a1ed86cc93d8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>31e75033-7b62-414b-9de3-372c111b0fcc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>43e8ebe4-3b6f-4feb-8543-1193d1f24463</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC UPDATE (PATCH - PUT)/PUT - Update User</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>76d7d6b7-6702-49b3-8cc5-be76bd32631d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec442350-a217-41ec-a893-1e026dcdb997</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2f50f7af-bebb-4db2-bc05-a958ec6843f0</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
