<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>Test suites consisting of all available post APIs</description>
   <name>TS - POST</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>ac0020d8-0731-43bb-8c9e-0e8a31017b1e</testSuiteGuid>
   <testCaseLink>
      <guid>5b809059-111c-466f-8c01-a69b35c3be6a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC - POST/POST - Create User</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>95411fbb-43c5-43aa-9a7e-59b9db70fab9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0cf9d3e9-9619-461d-a9b1-e477cdeda8fa</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>83b407b7-4b01-48c0-ab2e-6f5af5231b2b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC - POST/POST - Login Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>feda6f81-7b6a-487f-9008-16f995b636fa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC - POST/POST - Login Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>5e2827bd-b867-4a06-a6c7-f4d8501602cb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC - POST/POST - Register Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fce0c10f-436c-4a17-96fd-1fe7050a8333</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>49f9bb7d-b97d-4422-a74e-53704ed4f2b5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>62b188bc-6016-44c1-9256-acb6f0d08ddc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>52824e87-47a4-4138-9d2a-d840ad06e590</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC - POST/POST - Register with Empty Email</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>29086cd7-f55a-4f99-ae6f-f4b294eeb584</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4e91010f-a5ee-4fdb-9ec2-ef022cd9bf51</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>00e4473d-f71f-4ade-bb3a-1fd280d88c61</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6ecaf902-808e-481a-a6cc-be16db3c5e3b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC - POST/POST - Register with Empty Password</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>de5de4cc-8e23-4a5d-83d3-df775e970bfc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>da9a3b6b-718c-4ec9-86d0-9a8e6ec38a77</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>80b0ab7b-fd67-4a94-a721-d07c2e3c6ff7</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
